"""

Revision ID: 575dbddddba0
Revises:
Create Date: 2026-04-24 07:45:29.160709

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "575dbddddba0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_nonces",
        sa.Column(
            "nonce",
            sa.String(length=36),
            nullable=False,
            comment="Unique challenge string",
        ),
        sa.Column(
            "wallet_address",
            sa.String(length=64),
            nullable=False,
            comment="Wallet address this nonce is bound to",
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("nonce"),
    )
    op.create_index(
        op.f("ix_auth_nonces_wallet_address"),
        "auth_nonces",
        ["wallet_address"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column(
            "wallet_address",
            sa.String(length=64),
            nullable=False,
            comment="Hex-encoded Ed25519 public key (64 chars)",
        ),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("wallet_address"),
    )
    op.create_index(
        op.f("ix_users_wallet_address"), "users", ["wallet_address"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_wallet_address"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_auth_nonces_wallet_address"), table_name="auth_nonces")
    op.drop_table("auth_nonces")
    # ### end Alembic commands ###
